import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from "swiper";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import styles from "@/styles/Home.module.css";
import common from "@/styles/common.module.css";

let toggleflag = true;

let navToggle: HTMLElement | null;

let navToggle_header_links: HTMLElement | null;

const cards = [
  {
    id: 1,
    image: `/images/section_2_1.png`,
    month: "Dec",
    date: "12",
    heading: "The Musical Event",
    sub_heading: "Oakey Cultural Centre Manpo Hall",
    price: "$ 99.99 onwards",
  },
  {
    id: 2,
    image: `/images/section_2_2.png`,
    month: "Dec",
    date: "13",
    heading: "The Rosy DJ EVENT",
    sub_heading: "Oakey Cultural Centre Manpo Hall",
    price: "$ 99.99 onwards",
  },
  {
    id: 3,
    image: `/images/section_2_3.png`,
    month: "Dec",
    date: "14",
    heading: "The Crazy Eight night",
    sub_heading: "Oakey Cultural Centre Manpo Hall",
    price: "$ 99.99 onwards",
  },
  {
    id: 4,
    image: `/images/section_2_4.png`,
    month: "Dec",
    date: "12",
    heading: "The Ground War",
    sub_heading: "Oakey Cultural Centre Manpo Hall",
    price: "$ 99.99 onwards",
  },
  {
    id: 5,
    image: `/images/section_2_5.png`,
    month: "Dec",
    date: "13",
    heading: "The Friday Night",
    sub_heading: "Oakey Cultural Centre Manpo Hall",
    price: "$ 99.99 onwards",
  },
  {
    id: 6,
    image: `/images/section_2_6.png`,
    month: "Dec",
    date: "14",
    heading: "Game Of Basketball",
    sub_heading: "Oakey Cultural Centre Manpo Hall",
    price: "$ 99.99 onwards",
  },
];

const cards_2 = [
  {
    id: 1,
    heading: "Register",
    desctiption:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard make a type specimen book.",
  },

  {
    id: 2,
    heading: "Find event",
    desctiption:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard make a type specimen book.",
  },

  {
    id: 3,
    heading: "Select Your Seats",
    desctiption:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard make a type specimen book.",
  },
];

export default function Home() {
  React.useEffect(() => {
    if (typeof window !== "undefined") {
      navToggle = document.getElementById("navToggle");
      navToggle_header_links = document.getElementById(
        "navToggle_header_links"
      );
    }
  }, []);

  const handleClick = () => {
    const class_1 = `${common.d_none}`;

    const class_2 = `${styles.navToggle_header_link}`;

    if (toggleflag) {
      console.log("open");

      navToggle_header_links?.classList.remove(class_1);
      navToggle_header_links?.classList.add(class_2);
      toggleflag = false;
    } else {
      console.log("close");
      navToggle_header_links?.classList.remove(class_2);
      navToggle_header_links?.classList.add(class_1);
      toggleflag = true;
    }

    console.log(navToggle_header_links);
  };

  const pagination = {
    renderBullet: function (index: number, className: string) {
      return '<span class="' + className + '">' + (index + 1) + "</span>";
    },
    bulletActiveClass: `${styles["swiper-pagination-bullet-active"]}`,
  };

  return (
    <>
      <Head>
        <title>SnapTickets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={[styles.header].join(" ")}>
        <div
          className={[
            common.container,
            common.d_flex,
            common.align_center,
            styles.header_container,
          ].join(" ")}
        >
          <Link href={"/"}>
            <Image
              className={[common.cursor_pointer, styles.header_logo].join(" ")}
              src="/images/LOGO.png"
              width="241"
              height="49"
              alt="LOGO"
              priority
            />
          </Link>

          <ul
            className={[
              styles.header_links_display,
              common.grow,
              common.align_center,
              common.justify_evenly,
            ].join(" ")}
          >
            <li>
              <Link className={[common.header_font].join(" ")} href={"/"}>
                Organizer
              </Link>
            </li>
            <li>
              <Link className={[common.header_font].join(" ")} href={"/"}>
                Venue
              </Link>
            </li>
            <li>
              <Link className={[common.header_font].join(" ")} href={"/"}>
                Events
              </Link>
            </li>
            <li>
              <form
                className={[
                  styles.headr_search_form,
                  common.d_flex,
                  common.align_center,
                ].join(" ")}
              >
                <figure
                  className={[common.d_flex, common.align_center].join(" ")}
                >
                  <Image
                    src="/images/search_icon.png"
                    width="24"
                    height="23"
                    alt="LOGO"
                  />
                </figure>

                <input
                  type="text"
                  placeholder="Search for events , Play Activites"
                />
              </form>
            </li>
          </ul>

          {/* Sign Up and Login */}
          <div className={[styles.header_btn_root].join(" ")}>
            <button
              className={[
                common.btn_common,
                common.btn_1,
                styles.header_btn,
              ].join(" ")}
            >
              SIGN UP
            </button>
            <button
              className={[
                common.btn_common,
                common.btn_2,
                styles.header_btn,
              ].join(" ")}
            >
              LOGIN
            </button>
          </div>

          {/* nav_toggle_btn */}

          <button
            id="navToggle"
            onClick={handleClick}
            className={[styles.nav_toggle_btn].join(" ")}
          >
            <Image
              className={[styles.toggle_image].join(" ")}
              src="/images/nav_toggle_icon.png"
              alt="toggle nav"
              width={25}
              height={25}
              priority
            />
          </button>
        </div>

        {/* nav Toggle */}

        <ul id="navToggle_header_links" className={common.d_none}>
          <li className={[common.d_inline_block, common.w_100].join(" ")}>
            <Link
              href=""
              className={[
                common.header_font,
                common.w_100,
                common.d_flex,
                common.justify_center,
              ].join(" ")}
            >
              Organizer
            </Link>
          </li>

          <li className={[common.d_inline_block, common.w_100].join(" ")}>
            <Link
              href=""
              className={[
                common.header_font,
                common.w_100,
                common.d_flex,
                common.justify_center,
              ].join(" ")}
            >
              Venue
            </Link>
          </li>

          <li className={[common.d_inline_block, common.w_100].join(" ")}>
            <Link
              href=""
              className={[
                common.header_font,
                common.w_100,
                common.d_flex,
                common.justify_center,
              ].join(" ")}
            >
              Events
            </Link>
          </li>

          <li
            className={[
              common.d_flex,
              common.justify_center,
              common.w_100,
            ].join(" ")}
          >
            <button
              className={[
                common.btn_common,
                // common.btn_1,
                // styles.header_btn,
              ].join(" ")}
            >
              SIGN UP
            </button>
          </li>

          <li
            className={[
              common.d_flex,
              common.justify_center,
              common.w_100,
            ].join(" ")}
          >
            <button
              className={[
                common.btn_common,
                // common.btn_2,
                // styles.header_btn,
              ].join(" ")}
            >
              LOGIN
            </button>
          </li>

          <li
            className={[
              common.d_flex,
              common.justify_center,
              common.w_100,
            ].join(" ")}
          >
            <form
              className={[
                styles.headr_search_form,

                common.d_flex,
                common.align_center,
              ].join(" ")}
            >
              <figure
                className={[common.d_flex, common.align_center].join(" ")}
              >
                <Image
                  src="/images/search_icon.png"
                  width="24"
                  height="23"
                  alt="LOGO"
                />
              </figure>

              <input
                type="text"
                placeholder="Search for events , Play Activites"
              />
            </form>
          </li>
        </ul>
      </header>

      <main className={[styles.main, common.bg_color].join(" ")}>
        {/* section 1 */}
        <section className={[styles.section_1, common.relative].join(" ")}>
          <Swiper
            pagination={{
              clickable: true,
              type: "bullets",
              renderBullet: function (index: number, className: string) {
                return '<span class="' + className + '"> </span>';
              },
              bulletActiveClass: `${styles["swiper-pagination-bullet-active"]}`,
              bulletClass: `${styles["swiper-pagination-bullet"]}`,
            }}
            className={[styles.swiper].join(" ")}
            modules={[Pagination, Autoplay]}
            slidesPerView={1}
            loop={true}
            autoplay={{
              delay: 1500,
              disableOnInteraction: false,
            }}
          >
            <SwiperSlide className={[styles.swiperslide].join(" ")}>
              <div
                style={{ width: "100%", height: "100%", position: "relative" }}
              >
                <Image
                  src="/images/section_1_bg_image.png"
                  fill
                  // sizes="(max-width:1200px) 100vw"
                  alt="LOGO"
                  priority
                />
              </div>
            </SwiperSlide>

            <SwiperSlide className={[styles.swiperslide].join(" ")}>
              <Image
                src="/images/section_1_bg_image.png"
                fill
                sizes="(max-width:100vw)  (max-height:  600px) "
                alt="LOGO"
                priority
              />
            </SwiperSlide>

            <SwiperSlide className={[styles.swiperslide].join(" ")}>
              <Image
                src="/images/section_1_bg_image.png"
                fill
                sizes="(max-width:100vw)  (max-height:  600px) "
                alt="LOGO"
                priority
              />
            </SwiperSlide>

            <SwiperSlide>
              <Image
                src="/images/section_1_bg_image.png"
                fill
                sizes="(max-width:100vw)  (max-height:  600px) "
                alt="LOGO"
                priority
              />
            </SwiperSlide>

            <SwiperSlide>
              <Image
                src="/images/section_1_bg_image.png"
                fill
                sizes="(max-width:100vw)  (max-height:  600px) "
                alt="LOGO"
                priority
              />
            </SwiperSlide>
          </Swiper>
        </section>

        {/* section 2 */}
        <section className={[styles.section_2, common.width_100].join(" ")}>
          <div
            className={[
              common.container,
              common.d_flex_column,
              common.align_center,
              common.gap_15,
            ].join(" ")}
          >
            <h2
              className={[
                common.line_height_120,
                common.font_heading_common,
                common.w_100,
                common.d_flex,
                common.justify_start,
                styles.section_2_h2_1,
              ].join(" ")}
            >
              Upcoming Events
            </h2>

            {/*===== Cards ========== */}

            <div
              className={[
                common.d_flex,
                common.wrap,
                styles.section_2_card_root,
                common.gap_20,
              ].join(" ")}
            >
              {cards.map((card) => {
                return (
                  <div
                    key={card.id}
                    className={[
                      common.d_flex_column,
                      styles.section_2_card,
                    ].join(" ")}
                  >
                    <Image
                      className={[styles.s_2_img_1].join(" ")}
                      src={card.image}
                      width={385}
                      height={216}
                      alt="LOGO"
                      priority
                    />

                    <div
                      className={[
                        common.d_flex_column,
                        common.gap_15,
                        styles.section_card_content,
                      ].join(" ")}
                    >
                      <div
                        className={[
                          common.d_flex,
                          styles.section_card_content_1,
                          common.gap_15,
                        ].join(" ")}
                      >
                        <div
                          className={[common.d_flex_column, common.gap_5].join(
                            " "
                          )}
                        >
                          <h2
                            className={[
                              styles.card_month,
                              common.font_weight_400,
                              common.font_size_24,
                              common.line_height_29,
                            ].join(" ")}
                          >
                            {card.month}
                          </h2>

                          <h2
                            className={[
                              styles.card_date,
                              common.font_weight_500,
                              common.font_size_24,
                              common.line_height_29,
                            ].join(" ")}
                          >
                            {card.date}
                          </h2>
                        </div>

                        <div
                          className={[
                            common.d_flex_column,
                            common.wrap_initial,
                          ].join(" ")}
                        >
                          <h3
                            className={[
                              styles.card_heading,
                              common.font_weight_500,
                              common.font_size_20,
                            ].join(" ")}
                          >
                            {card.heading}
                          </h3>

                          <p
                            className={[
                              styles.card_sub_heading,
                              common.font_weight_300,
                              common.font_size_16,
                              common.line_height_18,
                            ].join(" ")}
                          >
                            {card.sub_heading}{" "}
                          </p>
                          <p
                            className={[
                              styles.card_price,
                              common.font_weight_500,
                              common.font_size_16,
                              common.line_height_18,
                              common.mr_t_10,
                            ].join(" ")}
                          >
                            {card.price}
                          </p>
                        </div>
                      </div>

                      <hr className={[styles.card_hr].join(" ")} />
                      <div
                        className={[
                          common.d_flex,
                          common.gap_10,
                          common.justify_center,
                          common.mr_t_10,
                          common.mr_b_18,
                          styles.card_btn_root,
                        ].join(" ")}
                      >
                        <button
                          className={[
                            common.btn_common,
                            common.btn_1,
                            styles.card_btn,
                          ].join(" ")}
                        >
                          BUY TICKETS
                        </button>
                        <button
                          className={[
                            common.btn_common,
                            common.btn_2,
                            styles.card_btn,
                          ].join(" ")}
                        >
                          READ MORE
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            <button
              className={[
                common.btn_3,
                common.mr_b_10,
                styles.btn_view_all,
              ].join(" ")}
            >
              VIEW ALL
            </button>
          </div>
        </section>

        {/* section 3 */}

        <section className={[styles.section_3, common.width_100].join(" ")}>
          <div
            className={[
              common.container,
              common.d_flex_column,
              common.mr_t_50,
              // common.align_center,
              // common.gap_15,
            ].join(" ")}
          >
            <h2
              className={[
                common.line_height_43,
                common.font_heading_common,
                common.w_100,
                common.d_flex,
                common.justify_start,
              ].join(" ")}
            >
              Becoming A Registered User
              <br />
              is Easy and The Smart Way to go!
            </h2>

            {/* section 3  card  */}
            <div
              className={[
                common.mr_t_25,
                common.mr_b_35,
                common.d_grid,
                common.gap_20,
                styles.section_3_card_root,
              ].join(" ")}
            >
              {cards_2.map((card) => {
                return (
                  <div
                    key={card.id}
                    className={[
                      common.d_flex_column,
                      styles.section_3_card,
                    ].join(" ")}
                  >
                    <h2
                      className={[
                        common.font_weigh_700,
                        common.font_size_24,
                        common.line_height_29,
                        common.d_flex_column,
                        // common.gap_40,
                      ].join(" ")}
                    >
                      <span
                        className={[styles.section_3_card_span_1].join(" ")}
                      >
                        {card.id}
                      </span>
                      <span
                        className={[styles.section_3_card_span_2].join(" ")}
                      >
                        {card.heading}
                      </span>
                    </h2>
                    <p className={[styles.font_p_common].join(" ")}>
                      {card.desctiption}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* section 4 */}
        <section className={[common.width_100, styles.section_4].join(" ")}>
          <div
            className={[
              common.container,
              common.d_flex,
              common.align_center,
              styles.section_4_root,
            ].join(" ")}
          >
            {/* sectin 4 left */}
            <div
              className={[
                styles.section_4_left,
                common.d_flex_column,
                common.justify_evenly,
                common.w_50,
              ].join(" ")}
            >
              <h2
                className={[
                  common.line_height_43,
                  common.font_heading_common,
                  common.w_100,
                  common.d_flex,
                  common.justify_start,
                ].join(" ")}
              >
                Becoming An Event Organizer
              </h2>
              <p className={[styles.font_p_common].join(" ")}>
                Access every show, even those that are sold out. <br />
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry&#39;s standard dummy
                text ever since the 1500s, when an unknown printer took a galley
                of type and scrambled it to make a type specimen book.
              </p>

              <button
                className={[common.btn_3, styles.btn_contanct_us].join(" ")}
              >
                CONTACT US
              </button>
            </div>

            {/* sectin 4 right */}
            <div
              className={[
                styles.section_4_right,
                common.d_flex_column,
                common.w_50,
                common.relative,
              ].join(" ")}
            >
              <figure
                className={[
                  styles.section_4_right_figure_1,
                  common.d_flex,
                  common.justify_center,
                  common.align_center,
                  common.w_100,
                  common.h_100,
                  common.relative,
                ].join(" ")}
              >
                <Image
                  src="/images/section_4_ellipse.png"
                  alt="ellipse"
                  width={167}
                  height={321}
                />
              </figure>

              <figure
                className={[
                  styles.section_4_right_figure_2,
                  common.d_flex,
                  common.justify_center,
                  common.align_center,
                  common.w_100,
                  common.h_100,
                  common.absolute,
                ].join(" ")}
              >
                <Image
                  src="/images/section_4_circle.png"
                  alt="ellipse"
                  width={284}
                  height={284}
                />
                <p
                  className={[
                    common.d_flex,
                    common.justify_center,
                    common.align_center,
                    common.w_100,
                    common.h_100,
                    common.absolute,
                    common.font_heading_common,
                    common.line_height_41,
                    styles.section_4_circle_content,
                  ].join(" ")}
                >
                  Organizer
                </p>
              </figure>
            </div>
          </div>
        </section>
      </main>

      <footer className={[styles.footer].join(" ")}>
        <div
          className={[
            common.container,
            common.h_100,
            common.d_flex_column,
            common.justify_evenly,
          ].join(" ")}
        >
          <div
            className={[
              common.d_flex,
              common.align_center,
              styles.footer_row_1,
            ].join(" ")}
          >
            <Link href={"/"}>
              <Image
                className={[common.cursor_pointer, styles.header_logo].join(
                  " "
                )}
                src="/images/footer_logo.png"
                width="241"
                height="49"
                alt="LOGO"
                priority
              />
            </Link>

            <ul
              className={[
                styles.footer_links,
                common.d_flex,
                common.grow,
                common.align_center,
              ].join(" ")}
            >
              <li>
                <Link className={[common.header_font].join(" ")} href={"/"}>
                  Organizer
                </Link>
              </li>
              <li>
                <Link className={[common.header_font].join(" ")} href={"/"}>
                  Venue
                </Link>
              </li>
              <li>
                <Link className={[common.header_font].join(" ")} href={"/"}>
                  Events
                </Link>
              </li>
            </ul>

            {/* Social Icons */}
            <div
              className={[
                styles.footer_icon_root,
                common.d_flex,
                common.gap_25,
              ].join(" ")}
            >
              <Link
                href={"/"}
                className={[common.d_flex, common.align_center].join(" ")}
              >
                <Image
                  src="/images/facebook.png"
                  width="24"
                  height="23"
                  alt="LOGO"
                />
              </Link>
              <Link
                href={"/"}
                className={[common.d_flex, common.align_center].join(" ")}
              >
                <Image
                  src="/images/instagram.png"
                  width="24"
                  height="23"
                  alt="LOGO"
                />
              </Link>

              <Link
                href={"/"}
                className={[common.d_flex, common.align_center].join(" ")}
              >
                <Image
                  src="/images/twitter.png"
                  width="24"
                  height="23"
                  alt="LOGO"
                />
              </Link>

              <Link
                href={"/"}
                className={[common.d_flex, common.align_center].join(" ")}
              >
                <Image
                  src="/images/youtube.png"
                  width="24"
                  height="23"
                  alt="LOGO"
                />
              </Link>

              <Link
                href={"/"}
                className={[common.d_flex, common.align_center].join(" ")}
              >
                <Image
                  src="/images/linkdln.png"
                  width="24"
                  height="23"
                  alt="LOGO"
                />
              </Link>
            </div>
          </div>

          <hr />
          <p
            className={[
              common.font_weight_400,
              common.font_size_16,
              styles.footer_copyright,
            ].join(" ")}
          >
            © Copyright 2022. All Rights Reserved. SnapIT.
          </p>
        </div>
      </footer>
    </>
  );
}
