import Head from "next/head";
import React from "react";

import styles from "@/styles/Home.module.css";
import common from "@/styles/common.module.css";

const index = () => {
  return (
    <>
      <Head>
        <title>SnapTickets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={[styles.main, common.bg_color].join(" ")}>
        {/* section 1 */}
        <section className={[styles.section_1].join(" ")}>
          mkfggdjfj
        </section>
      </main>
    </>
  );
};

export default index;
